# arm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 200

  # —Åontrollers for singular joint ------------------------------------
  uhvat_joint1_torque_controller:
    type: effort_controllers/JointEffortController
    joint: uhvat_joint_1
    pid: {p: 1000, i: 0.5, d: 10}
  uhvat_joint2_torque_controller:
    type: effort_controllers/JointEffortController
    joint: uhvat_joint_2
    pid: {p: 1000, i: 0.5, d: 10}
